services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - postgres_network
    command: >
      sh -c "
      while ! nc -z db 5432;
      do
        echo 'Waiting for PostgreSQL...';
        sleep 1;
      done;
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:${DATABASE_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
